name: OratioLingo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  timeago: ^3.6.1
  lottie: ^3.3.1
  shimmer: ^3.0.0
  firebase_app_check: ^0.3.2+6



  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
