// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm-Q54ymK_kZg-q9fCTTKibrSvN1WLBSs',
    appId: '1:260168634025:web:ac1da89be06418c4ade3b8',
    messagingSenderId: '260168634025',
    projectId: 'oratiolingo',
    authDomain: 'oratiolingo.firebaseapp.com',
    storageBucket: 'oratiolingo.firebasestorage.app',
    measurementId: 'G-V2RPTBP5XK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjqw-mNWaxpzw2ob-DkzWTkca3uZVPfuM',
    appId: '1:260168634025:android:1008332e9c69a6c1ade3b8',
    messagingSenderId: '260168634025',
    projectId: 'oratiolingo',
    storageBucket: 'oratiolingo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKTm4K808iVeUtDn1YODObSSjR3ltOHKI',
    appId: '1:260168634025:ios:0a5f6e5fb0aeff7aade3b8',
    messagingSenderId: '260168634025',
    projectId: 'oratiolingo',
    storageBucket: 'oratiolingo.firebasestorage.app',
    iosBundleId: 'com.example.gestos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKTm4K808iVeUtDn1YODObSSjR3ltOHKI',
    appId: '1:260168634025:ios:0a5f6e5fb0aeff7aade3b8',
    messagingSenderId: '260168634025',
    projectId: 'oratiolingo',
    storageBucket: 'oratiolingo.firebasestorage.app',
    iosBundleId: 'com.example.gestos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm-Q54ymK_kZg-q9fCTTKibrSvN1WLBSs',
    appId: '1:260168634025:web:95c351f385c68709ade3b8',
    messagingSenderId: '260168634025',
    projectId: 'oratiolingo',
    authDomain: 'oratiolingo.firebaseapp.com',
    storageBucket: 'oratiolingo.firebasestorage.app',
    measurementId: 'G-CD8FX4FZ55',
  );

}